### ISSUE TITLE
Issue with the install help

### ISSUE THREAD

**Issue by acerfon** [rogeriojorge/pyQIC#10]
Dear Rogerio,

In the install instructions, a dot is missing after the -e in this block:

cd pyQIC
pip install -e

You may want to clarify that for future users. Without the ., the install will not work.
(Also, the word install is misspelled just before this code block).

Regards,
Antoine

**Comment by rogeriojorge** [comment]
Hi Antoine, thanks! This is now being fixed with the latest pull request #11
